#+Title: Introduction Г  la Programmation Fonctionnelle avec Haskell
#+Author: Yann Esposito
#+Email: yann@esposito.host
#+Date: <2018-03-15 Thu>
#+LANGUAGE: fr
#+LANG: fr
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='/css/slides.css' />
* Introduction Г  la Programmation Fonctionnelle avec Haskell
*** main :: IO ()

#+BEGIN_SRC
в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳ
в–Ҳ                                                                                  в–Ҳ
в–Ҳ                        Initialiser l'env de dev                                  в–Ҳ
в–Ҳ                                                                                  в–Ҳ
в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳ
#+END_SRC

Install **stack**:

#+BEGIN_SRC bash
curl -sSL https://get.haskellstack.org/ | sh
#+END_SRC

Install **nix**:

#+BEGIN_SRC bash
curl https://nixos.org/nix/install | sh
#+END_SRC

** Programmation Fonctionnelle?
*** Von Neumann Architecture (1945)

#+BEGIN_SRC
           +--------------------------------+
           | +----------------------------+ |
           | | central processing unit    | |
           | | +------------------------+ | |
           | | |     Control Unit       | | |
+------+   | | +------------------------+ | |  +--------+
|input +---> | +------------------------+ | +--> output |
+------+   | | |  Arithmetic/Logic Unit | | |  +--------+
           | | +------------------------+ | |
           | +-------+---^----------------+ |
           |         |   |                  |
           | +-------v---+----------------+ |
           | |     Memory Unit            | |
           | +----------------------------+ |
           +--------------------------------+
#+END_SRC

made with http://asciiflow.com

*** Von Neumann vs Church

- programmer Г  partir de la machine (Von Neumann)
  + tire vers l'optimisation
  + mots de bits, caches, dГ©tails de bas niveau
  + actions sГ©quentielles
  + *1 siГЁcle d'expГ©rience*

. . .

- programmer comme manipulation de symbole (Alonzo Church)
  + tire vers l'abstraction
  + plus proche des reprГ©sentations mathГ©matiques
  + ordre d'Г©valuation non imposГ©
  + *4000 ans d'expГ©rience*

*** Histoire

- О»-Calculus, Alonzo Church & Rosser 1936
  - Foundation, explicit side effect no implicit state

. . .

- LISP (McCarthy 1960)
  - Garbage collection, higher order functions, dynamic typing

. . .

- ML (1969-80)
  - Static typing, Algebraic Datatypes, Pattern matching

. . .

- Miranda (1986) вҶ’ Haskell (1992вҖҘ)
  - Lazy evaluation, pure

** Pourquoi Haskell?
*** SimplicitГ© par l'abstraction

 *=/!\= SIMPLICITГү вү  FACILITГү =/!\=*

- mГ©moire (garbage collection)
- ordre d'Г©valuation (non strict / lazy)
- effets de bords (pur)
- manipulation de code (referential transparency)

. . .

SimplicitГ©: Probablement le meilleur indicateur de rГ©ussite de projet.

*** Production Readyв„ў

- rapide
  - Г©quivalent Г  Java (~ x2 du C)
  - parfois plus rapide que C
  - bien plus rapide que python et ruby
. . .
- communautГ© solide
  - 3k comptes sur Haskellers
  - >30k sur reddit /(35k rust, 45k go, 50k nodejs, 4k ocaml, 13k clojure)/
  - libs >12k sur hackage
. . .
- entreprises
  - Facebook (fighting spam, HAXL, ...)
  - beaucoup de startups, finance en gГ©nГ©ral
. . .
- milieu acadГ©mique
  - fondations mathГ©matiques
  - fortes influences des chercheurs
  - tire le langage vers le haut

*** Tooling

- compilateur (GHC)
- gestion de projets ; cabal, stack, hpack, etc...
- IDE / hlint ; rapiditГ© des erreurs en cours de frappe
- frameworks hors catГ©gorie (servant, yesod)
- ecosystГЁmes trГЁs matures et inovant
  - Elm (вҮ’ frontend)
  - Purescript (вҮ’ frontend)
  - GHCJS (вҮ’ frontend)
  - Idris (types dГ©pendants)
  - Hackett (typed LISP avec macros)
  - Eta (вҮ’ JVM)

*** QualitГ©

#+BEGIN_QUOTE
/Si Г§a compile alors il probable que Г§a marche/
#+END_QUOTE
. . .
- tests unitaires :
  chercher quelques erreurs manuellements
. . .
- /test gГ©nГ©ratifs/ :
  chercher des erreurs sur beaucoups de cas gГ©nГ©rГ©s alГ©atoirements
  & aide pour trouver l'erreur sur l'objet le plus simple
. . .
- /finite state machine generative testing/ :
  chercher des erreurs sur le dГ©roulement des actions
  entre diffГ©rents agents indГ©pendants
. . .
- *preuves*:
  chercher des erreur sur *TOUTES* les entrГ©es possibles
  possible Г  l'aide du systГЁme de typage

* Premiers Pas en Haskell
*** DON'T PANIC

#+BEGIN_SRC
в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв•—  в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв•— в–Ҳв–Ҳв–Ҳв•—   в–Ҳв–Ҳв•—в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв•—    в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв•—  в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв•— в–Ҳв–Ҳв–Ҳв•—   в–Ҳв–Ҳв•—в–Ҳв–Ҳв•— в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв•—в–Ҳв–Ҳв•—
в–Ҳв–Ҳв•”в•җв•җв–Ҳв–Ҳв•—в–Ҳв–Ҳв•”в•җв•җв•җв–Ҳв–Ҳв•—в–Ҳв–Ҳв–Ҳв–Ҳв•—  в–Ҳв–Ҳв•‘в•ҡв•җв•җв–Ҳв–Ҳв•”в•җв•җв•қ    в–Ҳв–Ҳв•”в•җв•җв–Ҳв–Ҳв•—в–Ҳв–Ҳв•”в•җв•җв–Ҳв–Ҳв•—в–Ҳв–Ҳв–Ҳв–Ҳв•—  в–Ҳв–Ҳв•‘в–Ҳв–Ҳв•‘в–Ҳв–Ҳв•”в•җв•җв•җв•җв•қв–Ҳв–Ҳв•‘
в–Ҳв–Ҳв•‘  в–Ҳв–Ҳв•‘в–Ҳв–Ҳв•‘   в–Ҳв–Ҳв•‘в–Ҳв–Ҳв•”в–Ҳв–Ҳв•— в–Ҳв–Ҳв•‘   в–Ҳв–Ҳв•‘       в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв•”в•қв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв•‘в–Ҳв–Ҳв•”в–Ҳв–Ҳв•— в–Ҳв–Ҳв•‘в–Ҳв–Ҳв•‘в–Ҳв–Ҳв•‘     в–Ҳв–Ҳв•‘
в–Ҳв–Ҳв•‘  в–Ҳв–Ҳв•‘в–Ҳв–Ҳв•‘   в–Ҳв–Ҳв•‘в–Ҳв–Ҳв•‘в•ҡв–Ҳв–Ҳв•—в–Ҳв–Ҳв•‘   в–Ҳв–Ҳв•‘       в–Ҳв–Ҳв•”в•җв•җв•җв•қ в–Ҳв–Ҳв•”в•җв•җв–Ҳв–Ҳв•‘в–Ҳв–Ҳв•‘в•ҡв–Ҳв–Ҳв•—в–Ҳв–Ҳв•‘в–Ҳв–Ҳв•‘в–Ҳв–Ҳв•‘     в•ҡв•җв•қ
в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв•”в•қв•ҡв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв•”в•қв–Ҳв–Ҳв•‘ в•ҡв–Ҳв–Ҳв–Ҳв–Ҳв•‘   в–Ҳв–Ҳв•‘       в–Ҳв–Ҳв•‘     в–Ҳв–Ҳв•‘  в–Ҳв–Ҳв•‘в–Ҳв–Ҳв•‘ в•ҡв–Ҳв–Ҳв–Ҳв–Ҳв•‘в–Ҳв–Ҳв•‘в•ҡв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв•—в–Ҳв–Ҳв•—
в•ҡв•җв•җв•җв•җв•җв•қ  в•ҡв•җв•җв•җв•җв•җв•қ в•ҡв•җв•қ  в•ҡв•җв•җв•җв•қ   в•ҡв•җв•қ       в•ҡв•җв•қ     в•ҡв•җв•қ  в•ҡв•җв•қв•ҡв•җв•қ  в•ҡв•җв•җв•җв•қв•ҡв•җв•қ в•ҡв•җв•җв•җв•җв•җв•қв•ҡв•җв•қ
#+END_SRC

- Haskell peut ГӘtre difficile Г  vraiment maГ®triser
- Trois languages en un:
  - Fonctionnel
  - Imperatif
  - Types
- Polymorphisme:
  - contexte souvent semi-implicite change le comportement du code.

*** Fichier de script isolГ©

Avec Stack: https://haskellstack.org

#+BEGIN_SRC haskell
#!/usr/bin/env stack
{- stack script
   --resolver lts-12.10
   --install-ghc
   --package protolude
-}
#+END_SRC

Avec Nix: https://nixos.org/nix/

#+BEGIN_SRC shell
#! /usr/bin/env nix-shell
#! nix-shell -i runghc
#! nix-shell -p "ghc.withPackages (ps: [ ps.protolude ])"
#! nix-shell -I nixpkgs="https://github.com/NixOS/nixpkgs/archive/18.09-beta.tar.gz"
#+END_SRC

*** Hello World! (1/3)

#+BEGIN_SRC haskell
-- hello.hs
main :: IO ()
main = putStrLn "Hello World!"
#+END_SRC

#+BEGIN_SRC
> chmod +x hello.hs
> ./hello.hs
Hello World!
#+END_SRC

#+BEGIN_SRC
> stack ghc -- hello.hs
> ./hello
Hello World!
#+END_SRC

*** Hello World! (2/3)

#+BEGIN_SRC haskell
main :: IO ()
main = putStrLn "Hello World!"
#+END_SRC

- ~::~ de type ;
- le type de ~main~ est ~IO ()~.
- ~=~ Г©galitГ© (la vrai, on peut interchanger ce qu'il y a des deux cotГ©s) ;
- le type de ~putStrLn~ est ~String -> IO ()~ ;
- application de fonction =f x= pas =f(x)=, pas de parenthГЁse nГ©cessaire ;

*** Hello World! (3/3)

#+BEGIN_SRC haskell
main :: IO ()
main = putStrLn "Hello World!"
#+END_SRC

- Le type ~IO a~ signifie: C'est une description d'une procГ©dure qui quand elle
  est Г©valuГ©e peut faire des actions d'IO qui retournera une valeur de type ~a~ ;
- ~main~ est le nom du point d'entrГ©e du programme ;
- Haskell runtime va chercher pour ~main~ et l'exГ©cute.

** What is your name?
*** What is your name? (1/2)

#+BEGIN_SRC haskell
main :: IO ()
main = do
  putStrLn "Hello! What is your name?"
  name <- getLine
  let output = "Nice to meet you, " ++ name ++ "!"
  putStrLn output
#+END_SRC

. . .

- l'indentation est importante !
- ~do~ commence une syntaxe spГ©ciale qui permet de sГ©quencer des actions ~IO~ ;
- le type de ~getLine~ est ~IO String~ ;
- ~IO String~ signifie: Ceci est la description d'une procГ©dure qui lorsqu'elle
  est Г©valuГ©e peut faire des actions IO et retourne une valeur de type ~String~.

*** What is your name? (2/2)

#+BEGIN_SRC haskell
main :: IO ()
main = do
  putStrLn "Hello! What is your name?"
  name <- getLine
  let output = "Nice to meet you, " ++ name ++ "!"
  putStrLn output
#+END_SRC

- le type de ~getLine~ est ~IO String~
- le type de ~name~ est ~String~
- ~<-~ est une syntaxe spГ©ciale qui n'apparait que dans la notation ~do~
- ~<-~ signifie: Г©value la procГ©dure et attache la valeur renvoyГ©e dans le nom
  Г  gauche de ~<-~
- ~let <name> = <expr>~ signifie que ~name~ est interchangeable avec ~expr~ pour
  le reste du bloc ~do~.
- dans un bloc ~do~, ~let~ n'a pas besoin d'ГӘtre accompagnГ© par ~in~ Г  la fin.

** Erreurs classiques
*** Erreur classique #1

#+BEGIN_SRC haskell
main :: IO ()
main = do
  putStrLn "Hello! What is your name?"
  let output = "Nice to meet you, " ++ getLine ++ "!"
  putStrLn output
#+END_SRC

#+BEGIN_SRC
/Users/yaesposi/.deft/pres-haskell/name.hs:6:40: warning: [-Wdeferred-type-errors]
    вҖў Couldn't match expected type вҖҳ[Char]вҖҷ
                  with actual type вҖҳIO StringвҖҷ
    вҖў In the first argument of вҖҳ(++)вҖҷ, namely вҖҳgetLineвҖҷ
      In the second argument of вҖҳ(++)вҖҷ, namely вҖҳgetLine ++ "!"вҖҷ
      In the expression: "Nice to meet you, " ++ getLine ++ "!"
  |
6 |   let output = "Nice to meet you, " ++ getLine ++ "!"
  |                                        ^^^^^^^
Ok, one module loaded.
#+END_SRC

*** Erreur classique #1

- ~String~ est ~[Char]~
- Haskell n'arrive pas Г  faire matcher le type ~String~ avec ~IO String~.
- ~IO a~ et ~a~ sont diffГ©rents

*** Erreur classique #2

#+BEGIN_SRC haskell
main :: IO ()
main = do
  putStrLn "Hello! What is your name?"
  name <- getLine
  putStrLn  "Nice to meet you, " ++ name ++ "!"
#+END_SRC

#+BEGIN_SRC
/Users/yaesposi/.deft/pres-haskell/name.hs:7:3: warning: [-Wdeferred-type-errors]
    вҖў Couldn't match expected type вҖҳ[Char]вҖҷ with actual type вҖҳIO ()вҖҷ
    вҖў In the first argument of вҖҳ(++)вҖҷ, namely
        вҖҳputStrLn "Nice to meet you, "вҖҷ
      In a stmt of a 'do' block:
        putStrLn "Nice to meet you, " ++ name ++ "!"
      In the expression:
        do putStrLn "Hello! What is your name?"
           name <- getLine
           putStrLn "Nice to meet you, " ++ name ++ "!"
  |
7 |   putStrLn "Nice to meet you, " ++ name ++ "!"
#+END_SRC

*** Erreur classique #2 (fix)

- Des parenthГЁses sont nГ©cessaires
- L'application de fonction se fait de gauche Г  droite

#+BEGIN_SRC haskell
main :: IO ()
main = do
  putStrLn "Hello! What is your name?"
  name <- getLine
  putStrLn ("Nice to meet you, " ++ name ++ "!")
#+END_SRC

* Concepts avec exemples
*** Concepts
- /style dГ©claratif & rГ©cursif/
- /immutabilitГ©/
- /puretГ©/ (par dГ©faut)
- /evaluation paraisseuse/ (par dГ©faut)
- /ADT & typage polymorphique/

*** /Style dГ©claratif & rГ©cursif/

#+BEGIN_SRC python
>>> x=0
... for i in range(1,11):
...     tmp = i*i
...     if tmp%2 == 0:
...       x += tmp
>>> x
220
#+END_SRC

#+BEGIN_SRC haskell
-- (.) composition (de droite Г  gauche)
Prelude> sum . filter even . map (^2) $ [1..10]
220
Prelude> :set -XNoImplicitPrelude
Prelude> import Protolude
-- (&) flipped fn application (de gauche Г  droite)
Protolude> [1..10] & map (^2) & filter even & sum
220
#+END_SRC

*** /Style dГ©claratif & rГ©cursif/

#+BEGIN_SRC python
>>> x=0
... for i in range(1,11):
...     j = i*3
...     tmp = j*j
...     if tmp%2 == 0:
...       x += tmp
#+END_SRC

#+BEGIN_SRC haskell
Prelude> sum . filter even . map (^2) . map (*3) $ [1..10]
Protolude> [1..10] & map (*3) & map (^2) & filter even & sum
#+END_SRC

*** /Style dГ©claratif & rГ©cursif/

- Contrairement aux languages impГ©ratifs la rГ©cursion n'est gГ©nГ©ralement pas chГЁre.
- tail recursive function, mais aussi Г  l'aide de la lazyness

*** /ImutabilitГ©/

#+BEGIN_SRC haskell
-- | explicit recursivity
incrementAllEvenNumbers :: [Int] -> [Int]
incrementAllEvenNumbers (x:xs) = y:incrementAllEvenNumbers xs
  where y = if even x then x+1 else x

-- | better with use of higher order functions
incrementAllEvenNumbers' :: [Int] -> [Int]
incrementAllEvenNumbers' ls = map incrementIfEven ls
  where
   incrementIfEven :: Int -> Int
   incrementIfEven x = if even x then x+1 else x
#+END_SRC

*** /PuretГ©/: Function vs Procedure/Subroutines

- Une /fonction/ n'a pas d'effet de bord
- Une /Procedure/ ou /subroutine/ but engendrer des effets de bords lors de son
  Г©valuation

*** /PuretГ©/: Function vs Procedure/Subroutines (exemple)

#+BEGIN_SRC haskell
dist :: Double -> Double -> Double
dist x y = sqrt (x**2 + y**2)
#+END_SRC


#+BEGIN_SRC haskell
getName :: IO String
getName = readLine
#+END_SRC

- *IO a* вҮ’ *IMPUR* ; effets de bords hors evaluation :
  - lire un fichier ;
  - Г©crire sur le terminal ;
  - changer la valeur d'une variable en RAM est impur.

*** /PuretГ©/: Gain, paralellisation gratuite

#+BEGIN_SRC haskell
import Foreign.Lib (f)
--  f :: Int -> Int
--  f = ???

foo = sum results
  where results = map f [1..100]
#+END_SRC

. . .

*~pmap~ FTW!!!!! Assurance d'avoir le mГӘme rГ©sultat avec 32 cЕ“urs*

#+BEGIN_SRC haskell
import Foreign.Lib (f)
--  f :: Int -> Int
--  f = ???

foo = sum results
  where results = pmap f [1..100]
#+END_SRC

*** /PuretГ©/: Structures de donnГ©es immuable

Purely functional data structures,
/Chris Okasaki/

ThГЁse en 1996, et un livre.

OpГ©rations sur les listes, tableaux, arbres
de complexitГ© amortie equivalent ou proche
(pire des cas facteur log(n))
de celle des structures de donnГ©es muables.

*** /Гүvaluation parraisseuse/: StratГ©gies d'Г©valuations

=(h (f a) (g b))= peut s'Г©valuer:

- =a= вҶ’ =(f a)= вҶ’ =b= вҶ’ =(g b)= вҶ’ =(h (f a) (g b))=
- =b= вҶ’ =a= вҶ’ =(g b)= вҶ’ =(f a)= вҶ’ =(h (f a) (g b))=
- =a= et =b= en parallГЁle puis  =(f a)= et =(g b)= en parallГЁle et finallement
  =(h (f a) (g b))=
- =h= вҶ’ =(f a)= seulement si nГ©cessaire et puis =(g b)= seulement si nГ©cessaire

Par exemple: =(def h (О»x.О»y.(+ x x)))= il n'est pas nГ©cessaire d'Г©valuer =y=,
dans notre cas =(g b)=

*** /Гүvaluation parraisseuse/: Exemple

#+BEGIN_SRC haskell
quickSort [] = []
quickSort (x:xs) = quickSort (filter (<x) xs)
                   ++ [x]
                   ++ quickSort (filter (>=x) xs)

minimum list = head (quickSort list)
#+END_SRC

Un appel Г  ~minimum longList~ ne vas pas ordonner toute la liste.
Le travail s'arrГӘtera dГЁs que le premier Г©lГ©ment de la liste ordonnГ©e sera trouvГ©.

~take k (quickSort list)~ est en ~O(n + k log k)~ oГ№ ~n = length list~.
Alors qu'avec une Г©valuation stricte: ~O(n log n)~.

*** /Гүvaluation parraisseuse/: Structures de donnГ©es infinies (zip)

#+BEGIN_SRC haskell
zip :: [a] -> [b] -> [(a,b)]
zip [] _  = []
zip _  [] = []
zip (x:xs) (y:ys) = (x,y):zip xs ys
#+END_SRC

#+BEGIN_SRC haskell
zip [1..] ['a','b','c']
#+END_SRC

s'arrГӘte et renvoie :

#+BEGIN_SRC haskell
[(1,'a'), (2,'b'), (3, 'c')]
#+END_SRC

*** /Гүvaluation parraisseuse/: Structures de donnГ©es infinies (2)

#+BEGIN_SRC haskell
Prelude> zipWith (+) [0,1,2,3] [10,100,1000]
[10,101,1002]
Prelude> take 3 [1,2,3,4,5,6,7,8,9]
[1,2,3]
#+END_SRC

#+BEGIN_SRC haskell
Prelude> fib = 0:1:(zipWith (+) fib (tail fib))
Prelude> take 10 fib
[0,1,1,2,3,5,8,13,21,34]
#+END_SRC

*** /ADT & Typage polymorphique/

Algebraic Data Types.

#+BEGIN_SRC haskell
data Void = Void Void -- 0 valeur possible!
data Unit = ()        -- 1 seule valeur possible

data Product x y = P x y
data Sum x y = S1 x | S2 y
#+END_SRC

Soit ~#x~ le nombre de valeurs possibles pour le type ~x~
alors:

- ~#(Product x y) = #x * #y~
- ~#(Sum x y)     = #x + #y~

*** /ADT & Typage polymorphique/: InfГ©rence de type

ГҖ partir de :

#+BEGIN_SRC haskell
zip [] _  = []
zip _  [] = []
zip (x:xs) (y:ys) = (x,y):zip xs ys
#+END_SRC

le compilateur peut dГ©duire:

#+BEGIN_SRC haskell
zip :: [a] -> [b] -> [(a,b)]
#+END_SRC

** ComposabilitГ©
*** ComposabilitГ© vs ModularitГ©

ModularitГ©: soit un ~a~ et un ~b~, je peux faire un ~c~.
  ex: x un graphique, y une barre de menu => une page
      ~let page = mkPage ( graphique, menu )~

ComposabilitГ©: soit deux ~a~ je peux faire un autre ~a~.
  ex: x un widget, y un widget => un widget
      ~let page = x <+> y~

Gain d'abstraction, moindre coГ»t.

*HypothГЁses fortes sur les ~a~*

*** Exemples

- *Semi-groupes* вҢ©+вҢӘ
- *Monoides* вҢ©0,+вҢӘ

- *CatГ©gories*  вҢ©obj(C),hom(C),вҲҳвҢӘ
- Foncteurs ~fmap~ (~(<$>)~)
- Foncteurs Applicatifs ~ap~ (~(<*>)~)
- Monades ~join~
- Traversables ~map~
- Foldables ~reduce~

* CatГ©gories de bugs Г©vitГ©s avec Haskell

*** Real Productions Bugsв„ў

Bug vu des dizaines de fois en prod malgrГ©:

  1. specifications fonctionnelles
  2. spГ©cifications techniques
  3. tests unitaires
  4. 3 envs, dev, recette/staging/pre-prod, prod
  5. Гүquipe de QA qui teste en recette

Solutions simples.

*** **Null Pointer Exception**: Erreur classique (1)

Au dГ©but du projet :

#+BEGIN_SRC javascript
int foo( x ) {
  return x + 1;
}
#+END_SRC

*** **Null Pointer Exception**: Erreur classique (2)

AprГЁs quelques semaines/mois/annГ©es :

#+BEGIN_SRC javascript
import do_shit_1 from "foreign-module";
int foo( x ) {
  ...
  var y = do_shit_1(x);
  ...
  return do_shit_20(y)
}
...
var val = foo(26/2334 - Math.sqrt(2));
#+END_SRC

. . .

#+BEGIN_SRC
в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳ       в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳ    в–Ҳв–Ҳв–Ҳ     в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ       в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ
в–Ҳв–Ҳв–Ҳ   в–Ҳв–Ҳ    в–Ҳв–Ҳв–Ҳ   в–Ҳв–Ҳв–Ҳ  в–Ҳв–Ҳв–Ҳ     в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳв–Ҳ     в–Ҳв–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ
в–Ҳв–Ҳв–Ҳ   в–Ҳв–Ҳ   в–Ҳв–Ҳв–Ҳ     в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ     в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳ   в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ
в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳ    в–Ҳв–Ҳв–Ҳ     в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ     в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ
в–Ҳв–Ҳв–Ҳ   в–Ҳв–Ҳв–Ҳ  в–Ҳв–Ҳв–Ҳ     в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ     в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ  в–Ҳв–Ҳв–Ҳ  в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ
в–Ҳв–Ҳв–Ҳ    в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ     в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ     в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ   в–Ҳ   в–Ҳв–Ҳв–Ҳ  в–Ҳ   в–Ҳ   в–Ҳ   в–Ҳ   в–Ҳ
в–Ҳв–Ҳв–Ҳ   в–Ҳв–Ҳв–Ҳ   в–Ҳв–Ҳв–Ҳ   в–Ҳв–Ҳв–Ҳ   в–Ҳв–Ҳв–Ҳ   в–Ҳв–Ҳв–Ҳ  в–Ҳв–Ҳв–Ҳ       в–Ҳв–Ҳв–Ҳ
в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳв–Ҳ       в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳ       в–Ҳв–Ҳв–Ҳв–Ҳв–Ҳ    в–Ҳв–Ҳв–Ҳ       в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ в–Ҳв–Ҳв–Ҳ
#+END_SRC

| *Null Pointer Exception*

*** Null Pointer Exception: Data type ~Maybe~

#+BEGIN_SRC haskell
data Maybe a = Just a | Nothing
...
foo :: Maybe a
...
myFunc x = let t = foo x in
  case t of
    Just someValue -> doThingsWith someValue
    Nothing -> doThingWhenNothingIsReturned
#+END_SRC

Le compilateur oblige Г  tenir compte des cas particuliers!
Impossible d'oublier.

*** Null Pointer Exception: Etat

- Rendre impossibe de fabriquer un Г©tat qui devrait ГӘtre impossible d'avoir.
- Pour aller plus loin voir, FRP, CQRS/ES, Elm-architecture, etc...

*** Erreur due Г  une typo

#+BEGIN_SRC haskell
data Foo x = LongNameWithPossibleError x
...
foo (LongNameWithPosibleError x) = ...
#+END_SRC

*Erreur Г  la compilation*:
Le nom d'un champ n'est pas une string
(voir les objets JSON).

*** Echange de parameters

#+BEGIN_SRC haskell
data Personne = Personne { uid :: Int, age :: Int }
foo :: Int -> Int -> Personne -- ??? uid ou age?
#+END_SRC

#+BEGIN_SRC haskell
newtype UID = UID Int deriving (Eq)
data Personne = Personne { uid :: UID, age :: Int }
foo :: UDI -> Int -> Personne -- Impossible de confondre
#+END_SRC

*** Changement intempestif d'un Etat Global

#+BEGIN_SRC haskell
foo :: GlobalState -> x
#+END_SRC

*~foo~ ne peut pas changer =GlobalState=*

* Organisation du Code
*** Grands Concepts

Procedure vs Functions:

| Gestion d'une configuration globale    |
| Gestion d'un Г©tat global              |
| Gestion des Erreurs                   |
| Gestion des IO                        |

*** Monades

Pour chacun de ces /problГЁmes/ il existe une monade:

| Gestion d'une configuration globale | ~Reader~ |
| Gestion d'un Г©tat global            | ~State~  |
| Gestion des Erreurs                 | ~Either~ |
| Gestion des IO                      | ~IO~     |

*** Effets

Gestion de plusieurs Effets dans la mГӘme fonction:

- MTL
- Free Monad
- Freer Monad

IdГ©e: donner Г  certaines sous-fonction accГЁs Г  une partie des effets seulement.

Par exemple:
- limiter une fonction Г  la lecture de la DB mais pas l'Г©criture.
- limiter l'Г©criture Г  une seule table
- interdire l'Г©criture de logs
- interdire l'Г©criture sur le disque dur
- etc...

*** Exemple dans un code rГ©el (1)

#+BEGIN_SRC haskell
-- |В ConsumerBot type, the main monad in which the bot code is written with.
-- Provide config, state, logs and IO
type ConsumerBot m a =
  ( MonadState ConsumerState m
  , MonadReader ConsumerConf m
  , MonadLog (WithSeverity Doc) m
  , MonadBaseControl IO m
  , MonadSleep m
  , MonadPubSub m
  , MonadIO m
  ) => m a
#+END_SRC

*** Exemple dans un code rГ©el (2)

#+BEGIN_SRC haskell
bot :: Manager
    -> RotatingLog
    -> Chan RedditComment
    -> TVar RedbotConfs
    -> Severity
    -> IO ()
bot manager rotLog pubsub redbots minSeverity = do
  TC.setDefaultPersist TC.filePersist
  let conf = ConsumerConf
             { rhconf = RedditHttpConf { _connMgr = manager }
             , commentStream = pubsub
             }
  void $ autobot
       & flip runReaderT conf
       & flip runStateT (initState redbots)
       & flip runLoggingT (renderLog minSeverity rotLog)
#+END_SRC


** RГЁgles *pragmatiques*

*** Organisation en fonction de la complexitГ©

#+BEGIN_QUOTE
Make it work, make it right, make it fast
#+END_QUOTE

- Simple: directement IO (YOLO!)
- Medium: Haskell Design Patterns: The Handle Pattern:
  https://jaspervdj.be/posts/2018-03-08-handle-pattern.html
- Medium (bis): MTL / Free / Freeer / Effects...
- Gros: Three Layer Haskell Cake:
 http://www.parsonsmatt.org/2018/03/22/three_layer_haskell_cake.html
  + Layer 1: Imperatif
  + OrientГ© Objet (Level 2 / 2')
  + Fonctionnel

*** 3 couches

- *Imperatif*:
  ReaderT IO
  + InsГ©rer l'Г©tat dans une ~TVar~, ~MVar~ ou ~IORef~ (concurrence)
- *OrientГ© Objet*:
  + Handle / MTL / Free...
  + donner des access ~UserDB~, ~AccessTime~, ~APIHTTP~...
- *Fonctionnel*: Business Logic ~f : Handlers -> Inputs -> Command~

*** Services / Lib

Service: ~init~ / ~start~ / ~close~ + methodes...
Lib: methodes sans Г©tat interne.

* Conclusion
*** Pourquoi Haskell?

- avantage compГ©titif: qualitГ© & productivitГ© hors norme
- change son approche de la programmation
- les concepts appris sont utilisables dans tous les languages
- permet d'aller lГ  oГ№ aucun autre langage ne peut vous amener
- Approfondissement sans fin:
  - ThГ©orie: thГ©orie des catГ©gories, thГ©orie des types homotopiques, etc...
  - Optim: compilateur
  - QualitГ©: tests, preuves
  - Organisation: capacitГ© de contraindre de trГЁs haut vers trГЁs bas

*** Avantage compГ©titif

- France, Europe du sud & Functional Programming
- CoГ»t Maintenance >> production d'un nouveau produit
- CoГ»t de la refactorisation
- "Make it work, Make it right, Make it fast" moins cher.

*** Pour la suite

A chacun de choisir, livres, tutoriels, videos, chat, etc...

- Voici une liste de resources : https://www.haskell.org/documentation
- Mon tuto rapide : [[http://yannesposito.com/Scratch/en/blog/Haskell-the-Hard-Way/][Haskell the Hard Way]]
- Moteurs de recherche par type : [[http://hayoo.fh-wedel.de][hayoo]] & [[http://haskell.org/hoogle][hoogle]]
- CommunautГ© & News : http://haskell.org/news & ~#haskell-fr~ sur freenode
- Libs: https://hackage.haskell.org & https://stackage.org

* Appendix
*** STM: Exemple (Concurrence) (1/2)

#+BEGIN_SRC java
class Account {
  float balance;
  synchronized void deposit(float amount){
    balance += amount; }
  synchronized void withdraw(float amount){
    if (balance < amount) throw new OutOfMoneyError();
    balance -= amount; }
  synchronized void transfert(Account other, float amount){
    other.withdraw(amount);
    this.deposit(amount); }
}
#+END_SRC

Situation d'interblocage typique. (A transfert vers B et B vers A).

*** STM: Exemple (Concurrence) (2/2)

#+BEGIN_SRC haskell
deposit :: TVar Int -> Int -> STM ()
deposit acc n = do
  bal <- readTVar acc
  writeTVar acc (bal + n)
withdraw :: TVar Int -> Int -> STM ()
withdraw acc n = do
  bal <- readTVar acc
  if bal < n then retry
  writeTVar acc (bal - n)
transfer :: TVar Int -> TVar Int -> Int -> STM ()
transfer from to n = do
  withdraw from n
  deposit to n
#+END_SRC

- pas de lock explicite, composition naturelle dans ~transfer~.
- si une des deux opГ©ration Г©choue toute la transaction Г©choue
- le systГЁme de type force cette opГ©ration a ГӘtre atomique:
   ~atomically :: STM a -> IO a~
