#+TITLE: How I Internet
#+SUBTITLE: (POSSE) Relaxing the Internet experience
#+AUTHOR: Yann Esposito
#+EMAIL: yann@esposito.host
#+DATE: [2019-09-14 Sat]
#+KEYWORDS: blog, self-hosting, web, zen, minimalism
#+DESCRIPTION: How I protect myself against attention grabbers and many social media anti-patterns.
#+OPTIONS: auto-id:t

#+begin_notes
*Sorry for the late reply*

Don't take it personnaly if I do not answer immediately to your comments or
questions.

I do not receive notification from most social media or even mail.
I do not have any social-media platform application on my phone.
I almost never check social media platform except GitHub.

I check my mails once in a while.
It can be a few times a day, but it is not unusual not to check my mail for
a few days or even an entiere week.

It is a protection against real-time notifications, and urgency feeling
that is harmful fof most people.

---------

TL;DR:

- I /POSSE[fn:posse]/; Publish Own Site, Syndicate Elsewhere:
  + I own my data I self host my blog, notes, my repositories, my bookmarks, etc...
  + I use espial[fn:espial] for self-hosted bookmarks and notes
  + I use note-red[fn:node-red] to publish my blogs, bookmarks and notes to
    twitter, sync bookmarks with pinboard[fn:pinboard]
- read Digital Minimalism[fn:dm]
- Control notifications
- Control real-time interactions
#+end_notes

[fn:posse]: https://indieweb.org/POSSE
[fn:dm] http://www.calnewport.com/books/digital-minimalism/
[fn:espial]: https://github.com/jonschoning/espial
[fn:node-red]: https://nodered.org
[fn:pinboard]: https://pinboard.in

* Intro
:PROPERTIES:
:CUSTOM_ID: intro
:END:

Our usage of the Internet changed a lot in recent years.
The book Digital Minimalism[fn:dm] explains quite clearly how Internet
and many social platforms are really useful but at the same can harm us.

The harm mostly come from social anti-pattern that are mostly hacking our
brain.
More precisely owr lower part of the brain, the one close to the instinct
which is quite difficult to tame.
This is why this is the preferred target of those "brain hacks".

Anti-features are:

- likes / retweets ; they provide no more benefit for us except we feel good
  by this social approval.
- comments are useful, the problem with comments is they generate a
  notification or if not, generate us to check quite often if our output
  has generated social approval or not.

So now, I how my own blog on my own server with my own domain name.
And I publish things, but I only check the outcome once or two times a day.
I receive no notification, I do not have any social media application on my
phone.
The social media "reactions" are filtered in my email, put in some
directory and checked once in a while (no more than twice a day, generally
only a few times a week).

The drawback is that it can feel rude for people not to be answered fast.
I am sorry, but it is a protection for my sanity.

* Producing
:PROPERTIES:
:CUSTOM_ID: producing
:END:
** Self Hosting
:PROPERTIES:
:CUSTOM_ID: self-hosting
:END:
The first important step is to self host most of my data.

Unfortunately this is not as straightforward as it should be.
The very first huge obstacle is owning a domain name and configuring the DNS.
It is WAY too complex to buy and control easily your own domain name.
I mean, once used to it, it is quite easy.
But I can't imagine someone not very used to computers to be able to
do all of that for himself in less than a few hours/days.

I wrote an [[file:new-blog.org][article]] sharing the details about my currentl blog platform.
I also describe how I intend to provide a respectful blog.

** TODO RSS
:PROPERTIES:
:CUSTOM_ID: rss
:END:
Describe that it is important to provide an RSS feed as a nice standardized
root to publishing.

** TODO Git Repositories
:PROPERTIES:
:CUSTOM_ID: git-repositories
:END:
** TODO Espial
:PROPERTIES:
:CUSTOM_ID: espial
:END:
Describe espial, and how I changed it.
** TODO node-red
:PROPERTIES:
:CUSTOM_ID: node-red
:END:
Describe node-red and how I use it.
* TODO Consuming
:PROPERTIES:
:CUSTOM_ID: consuming
:END:
** TODO Emacs elfeed
:PROPERTIES:
:CUSTOM_ID: emacs-elfeed
:END:

** TODO Mail
:PROPERTIES:
:CUSTOM_ID: mail
:END:
Only use mail

** TODO Github
:PROPERTIES:
:CUSTOM_ID: github
:END:
