#+TITLE: How I Internet
#+SUBTITLE: (POSSE) Relaxing the Internet experience
#+AUTHOR: Yann Esposito
#+EMAIL: yann@esposito.host
#+DATE: [2019-09-14 Sat]
#+KEYWORDS: blog, self-hosting, web, zen, minimalism
#+DESCRIPTION: How I protect myself against attention grabbers and many social media anti-patterns.
#+OPTIONS: auto-id:t

#+begin_notes
TL;DR:

- I /POSSE[fn:posse]/; Publish Own Site, Syndicate Elsewhere:
  + I own my data I self host my blog, notes, my repositories, my bookmarks, etc...
  + I use espial[fn:espial] for self-hosted bookmarks and notes
  + I use note-red[fn:node-red] to publish my blogs, bookmarks and notes to
    twitter, sync bookmarks with pinboard[fn:pinboard]
- read Digital Minimalism[fn:dm]
- Control notifications
- Control real-time interactions
#+end_notes

[fn:posse] https://indieweb.org/POSSE
[fn:dm] http://www.calnewport.com/books/digital-minimalism/
[fn:espial] https://github.com/jonschoning/espial
[fn:node-red] https://nodered.org
[fn:pinboard] https://pinboard.in

* Intro
:PROPERTIES:
:CUSTOM_ID: intro
:END:

Our usage of the Internet changed a lot in recent years.
The book Digital Minimalism[fn:dm] explains quite clearly how Internet
and many social platforms are really useful but at the same can harm us.

The harm mostly come from social anti-pattern that are mostly hacking our
brain.
More precisely our lower part of the brain, the one close to the instinct
which is quite difficult to tame.
This is why this is the preferred target of those "brain hacks".

Anti-features are:

- *notifications* ;  they are here to grab your attention when you are away
  doing something else.
- *likes / upvotes / retweets / pokes...* ; they are here to provide a "brain social
  sugar". They are not really useful but make us feel good by reinforing
  our feeling of social approval hacking our "social brain".
  More than that, we generally fall for most psychologic trick with those
  and make our production oriented to short content, mêmes, etc...
- *comments* ; Unlike likes or retweets, comment are a lot more useful,
  they can start a discussion. They still have two problems:
  1. Public comment are subject to spam, troll, attacks, etc... 
  2. Generally comments are associated to real-time notifications, and thus
     break a slower, calmer, more respectful communication channel. We are
     not all meant to react instantaneously.

My solution to take back the control, is to generate the content using my
own tools and broadcast those content to all other social media.
If people react to this on some social media, I'll get a mail that will be
put in a "social" folder.
I forbid myself to constantly check this social folder.


I do not have any social media application on my phone.
Everything goes through my email, filtered in some folder.
I only check those notifications in my email once or two times a day.
Sometime I only check the social mail folder once in a week.

As a result, I receive almost no notification.
I am almost never interrupted for those social interactions.

The main drawback of course is that I can give the impression that I am
rude by not answering immediately.
Unfortunately I am just protecting myself.

If I feel this is a too big problem, I'll create an auto-responder bot that
will nicely explain that I am sorry for the inconvenience but I can make a
long time to answer.

So being on the Internet, and in particular on the Web is mostly about
consuming information and producing information.

* Consuming
:PROPERTIES:
:CUSTOM_ID: consuming
:END:

Internet consumption evolved a lot.
Just think about the few first pages you visited a few years ago and today.

People tend to consume on their smartphones and generally inside a social
media platform dedicated application.
You are generally presented with an inifinite scroll media content.
Most of the time either video or photos.
Sometime with a link to some website, often behind a paywall.

And a lot about things easy to digest.
A cute cat, an image with a joke, a funny video, and once in a while like
very rare, a real important information about someone you care about or a
big news.
Most of the time, the news will be part of a polemic.
Because polemic is a very efficient attention grabber.

While I am totally fine with a bit of entertainment and polemic, the level
at which we are currently exposed right now can be quite harmful.

First thing to think about, why are we so eager to /news/?
Why not feel the same about old but great content?
Before all those news system, we were /active/ during our information
consumption.
We started from a search engine and /searched/ something.
Now, we still use search engines, but it is really about searching and not
trying to /discover/ something new.
This is also something to keep in mind.

** News
:PROPERTIES:
:CUSTOM_ID: news
:END:

So my entry point to news consumption are:

- highly selected RSS sources (for example HN posts with > 500 upvotes)
- [[https://lobste.rs][lobste.rs]]
- [[https://pinboard.in/popular/][popular pinboard.in bookmarks]]
- very few sub-reddits with small volume
- [[https://laarc.io][laarc.io]]
- [[https://fermatslibrary.com][Fermat's Library newsletter]]

I plan on generating RSS from those different sources with "smart filters".
Typically number of upvote filters for lobste.rs, laarc.io, sub-reddits,
but also number of bookmarks in popular pinboard, etc...

I really enjoy staying inside emacs as much as I can.
This is a clean, dense, text-oriented environment.

*** Emacs elfeed
:PROPERTIES:
:CUSTOM_ID: emacs-elfeed
:END:
As I said, one of my most useful tool to get news is RSS.
In particular I consume it inside Spacemacs using [[https://github.com/skeeto/elfeed][elfeed]].

I also use elfeed-org to organize my feeds ans I also take care to remove
feeds with too much volume.
Generally we shouldn't read more than a few articles a day.
** Mail
:PROPERTIES:
:CUSTOM_ID: mail
:END:
I also use my mail to get most of my notifications.
And I generally put the social notifications inside a folder and not
directly in my inbox.
That way I do not get any direct notification.
I check my social notifications once in a while.

** Github
:PROPERTIES:
:CUSTOM_ID: github
:END:
I still get notifications on Github because I use it a lot for my work.
But only email and web notifications, not desktop notifications.

So even for Github, I can take a few days to react.

* Producing
:PROPERTIES:
:CUSTOM_ID: producing
:END:

Another very important aspect of Internet and the Web is the ability to
produce an output and give it to someone else far away.

For now I only have two circles, myself and fully public.

I will certainly endup with strategies to put intermediate circles of
publications in the future.
It is good enough for now.

** Self Hosting
:PROPERTIES:
:CUSTOM_ID: self-hosting
:END:
A first important step for me was to self host most of my data.

I wrote an [[file:new-blog.org][article]] sharing the details about my currentl blog platform.
I also describe how I intend to provide a respectful blog.

** RSS
:PROPERTIES:
:CUSTOM_ID: rss
:END:
It was important for me to provide an RSS feed.
So people can know when I update my blog.
For now, I am not fully satisfied with it because my current system only
provide links but not the full content in the RSS feed.

But this is good enough for my current usage.

** Git Broadcast
:PROPERTIES:
:CUSTOM_ID: git-broadcast
:END:
I configured all my public repositories to be pushed both on my self-hosted
Gitlab instance and GitHub.

That way I host my own content, while still using to my advantages the
social feature of Github.

You can configure your git repositories to push to multiple url by:

#+begin_src
git remote set-url origin --push --add <remote-url>
git remote set-url origin --push --add <another-remote-url>
#+end_src

** Espial
:PROPERTIES:
:CUSTOM_ID: espial
:END:
[[https://github.com/jonschoning/espial][espial]] is an open-source, web-based bookmarking server.
It is a very easy to install single binary.
This is perfect if you want to self-host your bookmarks while having some publics.

This tool is written in Haskell, and I made a few pull requests to add RSS
feeds of my public bookmarks as well as an RSS feed for my public notes.

Notes, are simply text you save, you can make them public or private. I
tend to use it as my "micro-blogging". For the time when I just want to
write a short remark and not a full blog post article.
** node-red
:PROPERTIES:
:CUSTOM_ID: node-red
:END:
[[https://nodered.org][node-red]] is a tool that make it easy to write /flows/.
I use it to syndicate my self-hosted content to social media platforms.

Each time I save a new public bookmark, a new blog post, a new note, I
tweet it.
* Conclusion
:PROPERTIES:
:CUSTOM_ID: conclusion
:END:
So I described how while still using centralized social media platform, I
still own my data, I protect myself from new attention grabbing features
and design / UX pattern changes in those platforms.

Mostly, I take the positive aspect of those platform while not paying most
of the negative price.

For now my system is quite tailored made, and adapted to me.
I think we could imagine that we could offer that to more people by having
a single, easy to create platform.

The bit sad state, is that I know there are a few system that try to make
it easy for more people to self-host, or provide self-hosting for a smal
community or family.
But this is still reserved to technical people in my opinion.

I think we could be inspired by espia to create a simple small platform to
provide those feature to most people.

- ability to blog/microg blog and syndicate
- ability to publish securly private infos to a small group of friends and family
- generate RSS for different group of peoples

I would personally prefer that to a Federation platform (like Mastodon).
Unfortunately the federated network mostly replicate the anti-features of twitter, facebook,
and other social media platforms. While I believe we should change our
consumption habit.

RSS is already a great tool for that.

