#+TITLE: Welcome!
#+KEYWORDS: programming
#+AUTHOR: Yann Esposito
#+EMAIL: yann@esposito.host
#+DESCRIPTION:
#+LANGUAGE: en
#+LANG: en
#+OPTIONS: H:5
#+STARTUP: showeverything

@@html:
<div style="text-align:center">
<svg width="10em" viewBox="0 0 64 64">
<circle cx="32" cy="32" r="31" stroke="var(--base2)" stroke-width="1" fill="var(--base03)"/>
<circle cx="32" cy="32" r="16" stroke="var(--red)" stroke-width="1" fill="var(--orange)"/>
<circle cx="32" cy="32" r="8" stroke-width="0" fill="var(--yellow)"/>
<ellipse cx="32" cy="12" rx="16" ry="10" stroke-width="0" fill="var(--base3)"/>
</svg>
</div>
@@

Welcome to my personal website.
I generally talk about programming, maybe movies, or miscellaneous topics.
You can follow new articles via [[https://her.esy.fun/rss.xml][RSS]].
I also expose some of my presentations here.

- [[file:archive.org][articles]]
- [[file:slides.org][presentations]]

That website was created with the following constraints in mind by order of
priority:

1. *Respect Privacy*; no tracker of any sort (no ads, no google analytics, no
   referrer for all external links, etc...)
2. *Almost javascript free*; no js at all except for a single exception,
   pages containing Math formulae are displayed using mathjax. That means
   that even the CSS theme switcher does not use javascript.
3. *Accessibility*; should be easy to read on a text browser so people with
   disabilities could easily consume it.
4. *Nerdy*; should feel mostly like markdown text in a terminal and source code
   should be syntax highlighted.
5. *User friendly*; support your preferred light/dark theme by default but you
   can change it if you want.
6. *RSS*; you should be able to get informed when I add a new blog post.
7. *Frugal*; try to minimize the resources needed to visit my website; no
   javascript, no web-font, not too much CSS magic, not much images or really
   compressed one.

I talk about more details [[file:./posts/new-blog.org][here]].


#+begin_export html
<a href="https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fher.esy.fun%2Frss.xml">[Valid RSS]</a>
#+end_export
