#+TITLE: Welcome!
#+KEYWORDS: programming
#+AUTHOR: Yann Esposito
#+EMAIL: yann@esposito.host
#+DESCRIPTION:
#+LANGUAGE: en
#+LANG: en
#+OPTIONS: H:5
#+STARTUP: showeverything

Welcome to my personal website.

Here I will talk mostly about the life of a software developer.
So programming, functional programming in particular.

That website was created with the following constraints in mind by order of
priority:

1. *Respect Privacy*; no tracker of any sort (no ads, no google analytics, no
   referrer for all external links, etc...)
2. *almost javascript free*; no js at all except for a single exception,
   pages containing Math formula are displayed using mathjax. That means
   that event the CSS theme switcher does not use javascript.
3. *disability friendly*; should be easy to read on a text browser so people
   with disabilities could easily consume it
4. *nerdy*; should feel mostly like markdown text in a terminal and source code
   should be syntax higlighted.
5. *user friendly*; support your preferred light/dark theme by default but you
   can change it if you want.
6. *rss*; you should be able to get informed when I add a new blog post.
7. *frugal*; try to minize the resources needed to visit my website; no
   javascript, no webfont, not too much CSS magic, not much images or really
   compressed one.

I talk about more details [[file:./posts/new-blog.org][here]].
